---
name: test_run_qna

on:
  push:
    paths:
      - ".github/workflows/test_run_qna.yaml"
      - "CMD/bigfix_run_qna_win.bat"
      - "bash/bigfix_run_qna_debian.sh"
      - "bash/bigfix_run_qna_macos.sh"
    branches:
      - "**"

env:
  relevance: names of (files of it; folders of it) of folders ("/tmp";"/Windows/Temp")

jobs:
  test_run_qna:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: run qna windows
        if: runner.os == 'Windows'
        shell: cmd
        run: CMD/bigfix_run_qna_win.bat ${{ env.relevance }}
      - name: run qna linux
        if: runner.os == 'Linux'
        run: bash bash/bigfix_run_qna_debian.sh ${{ env.relevance }}
      # https://stackoverflow.com/questions/57946173/github-actions-run-step-on-specific-os
      - name: run qna mac
        if: runner.os == 'macOS'
        run: bash bash/bigfix_run_qna_macos.sh ${{ env.relevance }}
